# Generated by Django 5.1.4 on 2024-12-20 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.CharField(max_length=64, unique=True)),
                ('previous_block_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('difficulty', models.IntegerField()),
                ('size', models.IntegerField()),
                ('transaction_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_blocks', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('current_difficulty', models.PositiveIntegerField(default=0)),
                ('last_block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_supply', models.DecimalField(decimal_places=18, max_digits=30)),
                ('current_difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_data', models.JSONField()),
                ('log_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('node_ip', models.GenericIPAddressField()),
                ('node_port', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('is_miner', models.BooleanField(default=False)),
                ('is_validator', models.BooleanField(default=False)),
            ],
        ),
    ]
