# Generated by Django 5.1.4 on 2024-12-20 18:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='miner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mined_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchainstate',
            name='current_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.block'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='last_validated_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.block'),
        ),
        migrations.AddField(
            model_name='node',
            name='last_synced_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.block'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.node'),
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('contract_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bytecode', models.TextField()),
                ('abi', models.JSONField(blank=True, null=True)),
                ('creator_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.smartcontract'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=255)),
                ('token_symbol', models.CharField(max_length=10)),
                ('total_supply', models.DecimalField(decimal_places=18, max_digits=30)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=18, max_digits=30)),
                ('data', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 12, 20, 18, 46, 51, 189862, tzinfo=datetime.timezone.utc))),
                ('status', models.BooleanField()),
                ('signature', models.TextField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.block')),
                ('from_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('to_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=78)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('token_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='main.smartcontract')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='main.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='creation_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.transaction'),
        ),
        migrations.AddField(
            model_name='event',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.transaction'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['timestamp'], name='main_block_timesta_5d45a4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_address'], name='main_transa_from_ad_3b9eea_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_address'], name='main_transa_to_addr_c5a988_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['block'], name='main_transa_block_i_2b6b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransfer',
            index=models.Index(fields=['token_contract'], name='main_tokent_token_c_c25bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['contract'], name='main_event_contrac_1f7cd4_idx'),
        ),
    ]
